config/routes.rb
Rails.application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  root to: "articles#index"
  
  resources :comments
  get 'tag/:tag', to: 'articles#show_by_tag', as: :tag
  
  get 'articles/search', to: 'articles#search'
  resources :articles, only: [:index, :show, :new, :create, :update, :destroy]

  get 'category/:name', to: 'categories#show'

  get 'subscribe_category/:name', to: 'categories#subscribe'

  get '/unsubscribe/:signature' => 'categories#unsubscribe', as: 'unsubscribe'

end

app/models/article.rb
# :nodoc:
class Article < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :categories

  acts_as_commentable
  acts_as_taggable

  validates :user, :header, :announce, :body, presence: true
  # FIXME: NEED CREATE SERVICE LAYER FOR NOTIFICATION
  # after_update :subscribers_notification

  # FIXME: (LOGIC AND PLACE)
  # Assign to Article categories that user checked
  def assign_categories(categories)
    categories.each do |key, _value|
      if category = Category.find_by_name(key)
        self.categories << category
      end
    end
  end

  # it takes all subscribers of article categories
  def list_of_subscribers
    list = []
    self.categories.each do |category|
      category.subscribers.each do |user|
        list << user.id
      end
    end
    list.uniq!
    list - [self.user_id]
  end
end

app/controllers/articles_controller.rb
# Articles Controller
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:search, :index, :show, :show_by_tag]

  def index
    @articles = Article.where(approved: true).order('created_at DESC').page_kaminari(params[:page])
  end

  def show
    @article = Article.find(params[:id])
    if @article.approved
      @new_comment = Comment.build_from(@article, commenter_id)
    else
      redirect_to articles_url
    end
  end

  # FIXME: MOVE IT TO INDEX METHOD
  def show_by_tag
    @articles = Article.tagged_with(params[:tag]).page_kaminari(params[:page])
    render 'index'
  end

  def search
    if params[:search].nil? || params[:search].empty?
      redirect_to root_url
    elsif params[:search_by] == 'tags'
      @articles = Article.tagged_with(params[:search]).page_kaminari(params[:page])
      render 'index'
    elsif params[:search_by] == 'words'
      @articles = Article.search(params[:search], with: { approved: true }, page: params[:page], per_page: 6)
      @articles.context[:panes] << ThinkingSphinx::Panes::ExcerptsPane
      render 'search'
    else
      redirect_to root_url
    end
  end

  def new
    @article = Article.new
    @categories = Category.all
  end

  def create
    @article = Article.new(article_params)
    # FIXME: IS THIS NORMAL?
    @article.user_id = current_user.id
    # FIXME
    if params[:preview]
      render 'preview'
    elsif params[:category] && @article.save
      @article.assign_categories(params.require(:category))
      redirect_to articles_url
    else
      @categories = Category.all
      # FIXME
      render new_article_path
    end
  end

  def update
    if current_user.try(:admin?)
      @article = Article.find(params[:id])
      @article.update_attributes(approved: false)
    end
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.js
    end
  end

  private

  def article_params
    params.require(:article).permit(:header, :announce, :body, :tag_list)
  end
end

app/helpers/articles_helper.rb
# :nodoc:
module ArticlesHelper
end

app/views/articles/_tag_list.html.slim
  |Tags: 
  - @article.tag_list.each do |tag|
    = link_to tag, tag_path(tag)
    |  
    

app/views/articles/index.html.slim
- @articles.each do |article|
  div class=["article-#{article.id}"]
    .blog-post.blog-single-post
      .single-post-title
        h3
          = strip_tags(article.header)
      .single-post-content
        = strip_tags(article.announce)
      .single-post-info
        i.glyphicon.glyphicon-time
        =' article.updated_at.strftime("%d %^b, %Y")
        i.glyphicon.glyphicon-comment
        =' article.comment_threads.count
        = link_to "Read", article_path(article), class: "btn btn-primary btn-sm", style: "float: right;"
        - if current_user.try(:admin?)
          /FIXME Why "confirm:" dont work?
          = link_to "Удалить статью", article_path(article), method: :put, "data-confirm" => "Вы уверенены?", remote: true
      /! /.col-sm-4
.row
  center
    = paginate @articles

app/views/articles/new.html.slim
= form_for @article do |article|
  = article.label :header, "Заголовок"
  br
  = article.text_field :header, class: "form-control"
  p
  = article.label :announce, "Краткое описание"
  br
  = article.text_area :announce, class: "form-control"
  p
  = article.label :tag_list, "Теги (разделенные запятой)"
  br
  = article.text_field :tag_list, class: "form-control"
  p
  = article.label :body, "Ваша статья"
  br
  = article.text_area  :body, class: "form-control extended-redactor"
  p
  /FIXME
  = article.label :category, "Отметьте категории к которым относится статья:"
  br
  = fields_for :category do |c|
    - @categories.each do |category|
      =' c.check_box category.name, {}, true, false
      =' c.label category.name
      br
  p
  =' article.submit "Отправить на модерацию", class: "btn btn-primary"
  = article.submit "Предпросмотр", name: 'preview', class: "btn btn-primary"

app/views/articles/preview.html.slim
.blog-post.blog-single-post
  .single-post-title
    h3
      = strip_tags(@article.header)
  .single-post-content
    = sanitize(@article.body)
  .single-post-info
    i.glyphicon.glyphicon-time
    =' Time.now.strftime("%d %^b, %Y | ")
    |Tags: 
    - @article.tag_list.each do |tag|
      = tag
      |  
  = link_to 'Back to article', '', :onclick => 'history.go(-1)', class: "btn btn-primary btn-sm"

app/views/articles/search.html.slim
- @articles.each do |article|
  .blog-post.blog-single-post
    .single-post-title
      h3
        = sanitize(article.excerpts.header)
    .single-post-content
      = sanitize(article.excerpts.announce)
    .single-post-info
      i.glyphicon.glyphicon-time
      =' article.updated_at.strftime("%d %^b, %Y")
      i.glyphicon.glyphicon-comment
      =' article.comment_threads.count
      = link_to "Read", article_path(article), class: "btn btn-primary btn-sm", style: "float: right;"
      - if current_user.try(:admin?)
        /FIXME Why "confirm:" dont work?
        = link_to "Удалить", article_path(article), method: :delete,"data-confirm" => "Вы уверенены?"
/! /.col-sm-4
.row
  center
    = paginate @articles

app/views/articles/show.html.slim
.blog-post.blog-single-post
  .single-post-title
    h3
      = strip_tags(@article.header)
  .single-post-content
    = sanitize(@article.body)
  .single-post-info
    i.glyphicon.glyphicon-time
    =' @article.updated_at.strftime("%d %^b, %Y | ")
    = render 'tag_list'
  .all-comments
    = render partial: "comments/template", locals: {commentable: @article, new_comment: @new_comment}

app/views/articles/update.js.erb
$(".<%=j "article-#{@article.id}" %>").hide('drop', 1000);